### ISSUE TITLE
zmStats no longer being written for mods

### ISSUE THREAD

**Issue by GerardS0406** [plutoniummod/bug-tracker#2]
### What happened?

Plutonium T6 is no longer writing zmStats to mod folders anymore. This was working before the large update on November 27th, 2024 (r4516). Please note, that mpStats is still being written to mod folders for mp mods so this only affects zombies.

### Expected result

zmStats should be written to the mods folder.

### Steps to reproduce

1. Load a mod
2. Check Plutonium/storage/t6/mods/zm_anymod/
3. zmStats will either not be there or outdated

### Affected game(s)

BO2 Zombies (T6ZM)

### Affected component(s)

Client (game)

### Plutonium version

r4516 and up

### Additional information

Because of this, any new mods created using this version and later will receive the "Your online stats have been reset" on launch unless they have a pre-existing zmStats file. This theoretically can result in players not keeping their perma perks (or any other saved stat) for example while playing mods.

### Operating system

Windows 10

### Plutonium profile

https://forum.plutonium.pw/user/gerards0406

### Discord username

gerard0406

**Comment by ineedbots** [comment]
Fixed, thanks for the report, wait for the next release

**Comment by ineedbots** [comment]
Fix is currently on staging, waiting for prod release.

**Comment by GerardS0406** [comment]
> Fix is currently on staging, waiting for prod release.

thanks! will test it out now :)
